### ISSUE TITLE
Present Candela visualization types in list

### ISSUE THREAD

**Issue by ronichoudhury** [Kitware/candela#11]

**Comment by alex-r-bigelow** [comment]
For now, I'm just displaying the keys of candela.components in the vis library... I think that will do the job for now?

**Comment by ronichoudhury** [comment]
Sounds like that should be ok. Which commit does this?

**Comment by alex-r-bigelow** [comment]
28fbac7fb13a850fd9a0fd370d46c4f0c66becce does it.

BTW, my big refactoring push took a heckuvalot less time than I anticipated, so I'm going to move on to adding the mapping interface. I'm still seeing the scatterplot weirdness we encountered earlier, but there's no rush on that.

**Comment by ronichoudhury** [comment]
I'm only seeing a few top-level changes on that commit...

Sounds good re the mapping interface.

**Comment by alex-r-bigelow** [comment]
Whoops, must have copied the wrong SHA! Sorry about that. Here's the correct one: 9d2e0f3e6e9a61e7c492ecf5120aab15a101d514
