### ISSUE TITLE
Make reference app REST endpoints properly RESTful

### ISSUE THREAD

**Issue by ronichoudhury** [Kitware/candela#131]
e.g. GET endpoints should not change server state, etc.

**Comment by jeffbaumes** [comment]
I agree this is "icebox" - for @alex-r-bigelow's information this means before working on an icebox item we should have a discussion since it's labeled low priority.

**Comment by alex-r-bigelow** [comment]
This is part of #144 ... closing in favor of that issue (implicitly removing the icebox label)

**Comment by ronichoudhury** [comment]
I'd leave this open for now, until #144 demonstrates that it has actually solved it.
