### ISSUE TITLE
Identify "critical" mappings in a visualization

### ISSUE THREAD

**Issue by alex-r-bigelow** [Kitware/candela#138]
e.g. x and y for scatterplot, but not optional stuff like size / color

**Comment by jeffbaumes** [comment]
I think it's good to flip this around with a spec field to indicate something in optional, since I think the default should be that fields are required. The options spec would look like:

```
[
  {
    "name": "color",
    "optional": true,
    ...
  },
  ...
]
```

I can add this in a PR and @alex-r-bigelow can determine a reasonable way to display this in reslab.
