### ISSUE TITLE
"Prepare Girder" script

### ISSUE THREAD

**Issue by ronichoudhury** [Kitware/candela#144]
I think we need a more comprehensive version of the [populateGirder](https://github.com/Kitware/candela/blob/master/app/resonant-reference-app/examples/populateGirder.py) script that also creates the anonymous user, sets up the necessary collection and subfolders, in addition to uploading the example data sets. This would make it easier to get going with a fresh build of Girder and Resonant Laboratory, and prevent some errors that pop up when you're *not* set up quite right.

**Comment by alex-r-bigelow** [comment]
Feel free to assign this to whatever milestone you feel is appropriate

**Comment by ronichoudhury** [comment]
Well this is more of a developer concern than deployment, so I don't think it has to go with any of our current milestones. It's just something that ought to be done at some point, just to make things easier for new developers etc.

**Comment by jeffbaumes** [comment]
I'd also want to think about whether this is a Python script or an Ansible playbook. Ansible might be the better long-term deployment aide.

**Comment by ronichoudhury** [comment]
+1 for Ansible. I haven't had the chance to learn that yet for a specific work reason, so I'd be happy to look into this when the time is right.

**Comment by alex-r-bigelow** [comment]
I'm going to mark this fixed as of 70844029cc475514b867ada545abc3ded86327c2

Obviously there's still room for improvement—it would be awesome to have a script that sets up everything, i.e. mongo, girder, the admin account, database and filesystem assetstores, installs the plugin, and *then* does all the stuff that the script does now (creates the collection, folders, dataset and project items, and attaches their metadata).

**Comment by jeffbaumes** [comment]
Agree. Roni's deployment tasks should take care of most of this.

**Comment by ronichoudhury** [comment]
Yep, Ansible is the way to solve this for good. I'll be taking a look at starting that up soon.
