### ISSUE TITLE
Sometimes dismissal "X" in select data set dialog doesn't work

### ISSUE THREAD

**Issue by ronichoudhury** [Kitware/candela#148]
I am not able to reliably reproduce this, but it happened to me that I was "stuck" in the data set selection dialog, the only way to close it being to select a data set. The X button reacted as though I had clicked on it but otherwise did nothing.

If we're not able to reproduce this, we can close it.

**Comment by alex-r-bigelow** [comment]
Can't seem to replicate this, so I'll pull it off the milestone for now.

Do you remember if you had a project open when this happened? The semantics of whether you are allowed to close the overlay depends on this (it _should_ send you back to the starting screen if you don't have a project open)...

**Comment by ronichoudhury** [comment]
How do you end up in the data set selection overlay if you *don't* have a project open?

**Comment by alex-r-bigelow** [comment]
If you click the "start with a dataset" button, it brings up the same interface—it just does slightly different things depending on whether you already have a project open (replace the dataset vs create a new project with the dataset). It will probably need a redesign when we start supporting multiple datasets anyway, so there's a chance this problem will disappear then? Or if we can replicate it, I'm happy to fix it now.

**Comment by ronichoudhury** [comment]
Ah of course, from the splash screen.

I think I did have a project open but I'm not sure. I'm ok with closing this issue now, since I'm the only one who saw the problem, and under circumstances that may have been wonky in any case (wrong collection name after the application rebranding, etc.).
