### ISSUE TITLE
Need a way to get back to splash screen

### ISSUE THREAD

**Issue by ronichoudhury** [Kitware/candela#152]
Currently the only way to "start over" is to manually clear the URL fragments and hit enter, or to log out (if you are logged in already). I feel like there ought to be an easy in-app way to do that as well, since it provides a familiar entry point to the application no matter what state the user is currently in. I think this could appear in the hamburger menu as something like "start over" or "return to home screen" etc.

**Comment by alex-r-bigelow** [comment]
I sneakily added a "Close project" option that does this while I was fixing up the menu in 700b0c6265293a686768cc74757cae150913db8a

**Comment by ronichoudhury** [comment]
Oh! Very nice!
