### ISSUE TITLE
Fix path on clean

### ISSUE THREAD

**Issue by jeffbaumes** [Kitware/candela#153]
I keep seeing this on `npm run build`:

```
clean-webpack-plugin: /Users/jeff/code/candela/config/build/* has been removed.
```

Seems it should be:

```
clean-webpack-plugin: /Users/jeff/code/candela/build/* has been removed.
```

**Comment by ronichoudhury** [comment]
Oops. This happened when I moved the webpack config files into a dedicated directory to corral them. It's unfortunately not as simple as shoving another `..` before the path - looking into it.
