### ISSUE TITLE
Handle lat/lon matchings intelligently

### ISSUE THREAD

**Issue by alex-r-bigelow** [Kitware/candela#175]
See this discussion: https://github.com/Kitware/candela/pull/171#issuecomment-216887014

Interestingly, it seems that we're pulling stuff from the vis side to learn about the data, at least conceptually (datalib is really a vega thing, minerva has its cool lat/lon detection stuff). Is there something bigger here that should be part of candela (where, given a dataset, a component can optionally suggest data types and/or matchings)?

**Comment by ronichoudhury** [comment]
I think there's definitely an opportunity here. Maybe @mgrauer should add this topic to his fact-finding mission...?

**Comment by mgrauer** [comment]
Let's talk about this next week.

**Comment by ronichoudhury** [comment]
Excellent.

**Comment by alex-r-bigelow** [comment]
Currently, Resonant Lab (technically) supports mapping mystery objects to visualizations that expect them. Beyond that, we're thinking that this would fall under the category of data reshaping, in which a separate tool should be used.
