### ISSUE TITLE
Certain "Log in" and "Register" links don't work

### ISSUE THREAD

**Issue by ronichoudhury** [Kitware/candela#176]
To reproduce:

1. Go to the application front page while being logged out.
2. Click "Create an empty project".
3. Open the hamburger menu and click "Close project".
4. You should see the new project in the "public scratch space" portion of the modal dialog.
5. Click on the "Log in" link in that section. **Nothing happens.**
6. Click on the "Register" link in that section. **Nothing happens.**

**Comment by alex-r-bigelow** [comment]
Hmm... following these instructions, I get the log in and register dialogs when I click on the links. I assume nothing is showing up in the console?

**Comment by ronichoudhury** [comment]
I showed Alex how this bug manifests on my build... he is on the case :mag_right:
