### ISSUE TITLE
Heatmap labels change on render

### ISSUE THREAD

**Issue by ronichoudhury** [Kitware/candela#180]
The heatmap has a weird behavior - every time it renders, the labels on the y-axis can change. To reproduce:

1. Build the project (e.g. `npm run build`).
2. Start the testing server with `npm run demo`.
3. Visit http://localhost:3000/#heatmap in a browser.
4. Observe the lowest number on the y-axis (should be `429`).
5. Change the size of your browser window to force resize-based re-render.
6. Observe the lowest number on the y-axis again (should be larger than `429`).

**Comment by ronichoudhury** [comment]
Make sure to solve #181 once this is fixed.

**Comment by jeffbaumes** [comment]
This is because it defaults to using the internal `id` field from Vega as the name, which apparently changes on re-render. In the case that no id is provided, we should probably just not display the names along the y-axis, since they are meaningless anyway.
