### ISSUE TITLE
Update matching indicator

### ISSUE THREAD

**Issue by jeffbaumes** [Kitware/candela#214]
Currently, the matching indicator (like 3 / 3) computes the first number as the number of matchings, instead of the number of visual attributes that are filled. This can be misleading for multiple-field inputs. For example, I would think this should say 2 / 3 but it says 3 / 3. The first number can easily get larger than the second number, which is confusing.

![screen shot 2016-05-13 at 11 14 14 am](https://cloud.githubusercontent.com/assets/81305/15252526/528027f4-18fc-11e6-9924-98e1f7275345.png)

**Comment by jeffbaumes** [comment]
Another related update is to make the indicator not a button, since clicking the button does nothing other than expand/collapse the panel.

**Comment by alex-r-bigelow** [comment]
True. I was holding off on this until we resolved #138, but it's good to make the UI part of this a separate issue.

As a button, this would probably be a cool place to auto-configure or auto-detect "interesting" mappings (clicking it would bring up that interface). But for now, I agree it should probably just be text. I'll make that change in the current ui-fixes branch and wait for another LGTM.
