### ISSUE TITLE
Switching visualizations causes memory leak

### ISSUE THREAD

**Issue by alex-r-bigelow** [Kitware/candela#226]
Switching visualizations repeatedly (especially with a dataset with a lot of attributes) will eventually crash the tab

**Comment by alex-r-bigelow** [comment]
Note: to replicate, @manthey has a great dataset (requires about 10 attribute switches to crash the tab)

**Comment by jeffbaumes** [comment]
When we tackle this we may want to examine this https://github.com/vega/vega/issues/594

**Comment by alex-r-bigelow** [comment]
As far as my stress tests have shown, this appears to be fixed—I'll close it for now. @manthey, feel free to reopen if you run into this again.

**Comment by ronichoudhury** [comment]
:tada:
