### ISSUE TITLE
Query language does not handle type coercion

### ISSUE THREAD

**Issue by alex-r-bigelow** [Kitware/candela#307]
Example of the problem:
- The filters are created in terms of the user's type coercion settings. Meaning that `cylinders not in [4,5,6]` is expecting the data to already be a number... but the filter is applied in a setting that is unaware of type coercion parameters (e.g. `astToFunction` produces something that operates in python land, iterating over what are likely rows of CSV strings).

- We need to do one of the following:
1) Somehow make type coercion a native part of the query language
2) Somehow reach into whatever process is actually handling the data, and convert values on the fly before they reach the query function / mongo query
3) Actually go in and change the native values in the database / flat file per the user's coercion settings

1 and 3 may or may not be possible / practical (@ronichoudhury, thoughts on this?). But the problem with 2 is it requires adding a lot of app-specific logic in places that it probably shouldn't exist, such as providing a custom preprocessing function to the download endpoint as an `extraParameter` before the filter is applied... and that function would somehow have be executed in python for flat files, as well as inside mongodb, etc.

Thoughts on how we should proceed? I'm leaning toward 1 if it's possible—that seems the cleanest to me.

Minor, but related points:
- We have semi-specialized coercion logic in `general_purpose/binUtils.js`, e.g. we use Javascript nuances like truthy/falsey values for boolean conversion. Ideally, we'd like to avoid duplicating this code with all its nuances, but that may be unavoidable.
- Our decision here will probably determine a lot about how we handle corner case values like `"cylinders" not in [NaN]`

**Comment by jeffbaumes** [comment]
I think that 3 is out - the data should just be the data and the coercions should happen on-the-fly. The other two options are basically variations on how to get the coercion settings over to the server. 2 does not sound great since the general data extraction should not need to know about coercion.

1 is better, but another way to solve it is to send the coercion data separately - it does not necessarily need to be part of the query language. Could something simple like an extra argument with the information like `{ "cylinder": "integer", ... }` work?

**Comment by alex-r-bigelow** [comment]
The problem is, where would that argument be implemented? If I understand it correctly, the plan is for data extraction to accept a filter parameter. Because coercion has to happen *before* the filter is applied, data extraction would also have to accept (and implement the logic for) that extra argument. If we don't want that, the only other way I can see us sneaking it in would be as part of the query language.

**Comment by alex-r-bigelow** [comment]
If none of these are palatable, I guess there's one more option:
4) We go back to implementing data extraction ourselves in Resonant Laboratory, ignoring the download endpoint

Obviously, this one stinks for a lot of reasons—it's down there with option 3, but I'm listing it here to be thorough.

**Comment by ronichoudhury** [comment]
Cribbing from languages like Haskell, we could certainly implement type coercion semantics by tagging field names with types, something like `cylinder::number not in [3, 4, 5]`. The type tag would be optional, and would be implemented in the query language by adjoining an optional datum to the AST nodes for "identifiers". And we can "escape" double colons in field names by implementing double quote handling in that syntax rule.

My intuition is that this would be a relatively simple thing to do. But if we go this route, I'll need to iterate with you a bit IRL to understand the various use cases that have popped / could pop up.

**Comment by alex-r-bigelow** [comment]
I think Postgres uses that notation natively as well. 😎 

It should work pretty well for `astToFunction`—we'd just have to be careful to keep the semantics the same (e.g. do Javascript-style conversions in python).

It could be tricky for `astToMongo`—[type conversion in mongo](http://stackoverflow.com/questions/3521601/is-it-possible-to-cast-in-a-mongodb-query), while possible, ignores any indexes. But I don't see any way around that problem with mongo, regardless of which strategy we choose (apart from 3).

**Comment by jeffbaumes** [comment]
If it's relatively simple, I'm good with adding it to the query language.

**Comment by alex-r-bigelow** [comment]
Fixed in #320
