### ISSUE TITLE
Edit project description from Resonant Lab

### ISSUE THREAD

**Issue by alex-r-bigelow** [Kitware/candela#359]
Add a field to edit the item description markdown from somewhere in Resonant Lab (probably a separate page in the settings dialog?).

**Comment by alex-r-bigelow** [comment]
Closing as duplicate of #360

**Comment by ronichoudhury** [comment]
Oops, sorry, I didn't realize this was the same thing as my issue :crying_cat_face: 

I do prefer to phrase it as a "notes" field (regardless of how it gets implemented in Girder), just to keep it more feature-centric.
