### ISSUE TITLE
"Link to a new dataset" may be confusing

### ISSUE THREAD

**Issue by ronichoudhury** [Kitware/candela#364]
The purpose of this option is to allow a dataset already in Girder to be used in Resonant Laboratory. As such, it may need a more precise description than "linking", which isn't quite what is going on.

**Comment by alex-r-bigelow** [comment]
In the future, I was planning to use the same field to paste other kinds of links (e.g. files hosted on dropbox). Linking to an existing girder item by ID is really a corner case that, really, only we developers are likely to use.

I agree for now we should change it, but maybe change it back if/when we add support for linked files?

**Comment by ronichoudhury** [comment]
This is one of those cases where what we imagine might balloon into a lot
of unexpected use cases. For instance, if someone uses a Python script to
upload a bunch of datasets, they may want to use this function to bootstrap
some of the datasets into Resonant Laboratory, etc. But I see what you mean
about it being a minority use case. I'd say let's figure out the wording to
use now, and then if we want to actually link in external files later, add
"link to dataset" back in as another option.
