### ISSUE TITLE
New projects start with high numbers

### ISSUE THREAD

**Issue by alex-r-bigelow** [Kitware/candela#367]
Especially when users are logged out, their project names will likely be something like "Untitled Project (31415)". Perhaps there is a better way to start out with a project name?

**Comment by manthey** [comment]
Dates and times are popular choices instead - "Project 2016-08-24 09:32"

**Comment by ronichoudhury** [comment]
I think numbers - even high ones - are fine. They are easier to keep in mind for a moment than datetimes. And the problem goes away once the user renames the project. Datetimes work too of course.

A third option is to do what github does when recommending project names: combine an adjective and a noun from some long list of inoffensive words to form a name. If the expectation is to rename a project in any case, then maybe this is the most palatable option.

**Comment by ronichoudhury** [comment]
Closing, as the current behavior is fine.
