### ISSUE TITLE
vagrant up on resonant lab failed on missing GirderClient

### ISSUE THREAD

**Issue by curtislisle** [Kitware/candela#386]
just tried a new vagrant up on the app/resonant-laboratory application, but girder configuration problem prevented provisioning from finishing.  When I access localhost:8080, the regular Girder web-client responds instead of a resonant-lab instance. 

TASK [Create Girder admin user] ************************************************
fatal: [reslab]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1473687924.55-155165532428841/girder\", line 2972, in <module>\r\n    class GirderClientModule(GirderClient):\r\nNameError: name 'GirderClient' is not defined\r\n", "msg": "MODULE FAILURE", "parsed": false}

**Comment by ronichoudhury** [comment]
Hi @curtislisle! What branch/revision are you doing this from?

**Comment by curtislisle** [comment]
@ronichoudhury , thanks for looking!  Below is the top of the git log.  I did a pull and switched to ansible-update branch.  Did I configure wrong? 

$git log
commit b0e60d07a4732608b51153c8c38c5c735fe1e62d
Author: Roni Choudhury <roni.choudhury@kitware.com>
Date:   Fri Sep 9 12:56:20 2016 -0400
    Change revisions for girder and candela; stop using girder_client
.....

$ git status
On branch ansible-update
Your branch is up-to-date with 'origin/ansible-update'.
nothing to commit, working directory clean

**Comment by ronichoudhury** [comment]
No, you did everything right. Let me take a look at the provisioning to see
how to patch up the deficiency...

**Comment by ronichoudhury** [comment]
Curt, if you could pull and try again... I think I fixed the problem that
you were encountering before.

If it doesn't work, you can also try starting fresh ("vagrant destroy"
followed by "vagrant up").

Let me know what happens!

roni

**Comment by curtislisle** [comment]
git pull and reprovisioning (vagrant up; vagrant provision) worked first time.  The interface is up and working. Thanks!

**Comment by ronichoudhury** [comment]
Fantastic! I'll close the issue; please re-open if you run into further trouble on this topic.
