### ISSUE TITLE
Mult-bar application of barchart in Res Lab

### ISSUE THREAD

**Issue by curtislisle** [Kitware/candela#420]
Use case:  a multi-column CSV file is opened. the bar chart visualization is selected and more than one column of data is connected to the Y-value.  I would like to have a separate bar side-by-side for each attribute.  This is might be easier to interpret if we added a stacked bar visualization and then mapped multiple attributes to sections of the bar.  

However, it might be nice to have a default behavior of multiple bars per "X position" if someone connects more than one numerical attribute to the Y-value of the regular bar chart.  I am suggesting this because of a first-time impression using Res Lab by an scientific colleague of mine. 

Could be related to #218

**Comment by jeffbaumes** [comment]
Yes I believe this is a repeat of #218. Makes me know it is a higher priority though, thanks for the feedback.
