### ISSUE TITLE
Change package entry point in package.json to minified file

### ISSUE THREAD

**Issue by ronichoudhury** [Kitware/candela#437]
We should verify that this is a normal practice before pulling the trigger.

**Comment by jeffbaumes** [comment]
Also should update the link in pycandela to point to the minified file.

**Comment by jeffbaumes** [comment]
Looks like many popular libs like lodash, jquery, d3 do not use minified versions as their entrypoint. I feel we should close this, but maybe document the unpkg URL for the minified version if that's desired.

**Comment by ronichoudhury** [comment]
Actually that makes sense. If the URL doesn't have `min` in it, I feel it should not be pointing to a minified version.

Documenting the unpkg URL is a good idea.

**Comment by ronichoudhury** [comment]
Closing in favor of #438
