### ISSUE TITLE
Shapes don't appear in legend of "scatter" example

### ISSUE THREAD

**Issue by ronichoudhury** [Kitware/candela#511]
Note that the shapes *do* appear in the `scatter-solid` example, which is puzzling.

**Comment by jeffbaumes** [comment]
Can't reproduce locally, and the test image has the shape legend so it appears in CI as well.

**Comment by ronichoudhury** [comment]
Good to know. If it's only a problem for me, I'll go ahead and close this.

**Comment by jeffbaumes** [comment]
Yes, it appears to be. I'll close for now.
