### ISSUE TITLE
Write a Python script to upload some example datasets to Girder

### ISSUE THREAD

**Issue by ronichoudhury** [Kitware/candela#58]

**Comment by alex-r-bigelow** [comment]
I'm starting in on this... any thoughts on a separate repo to house the example datasets/toolchains?

**Comment by ronichoudhury** [comment]
Is there a need for them to be in a separate repo? I just pictured a few example datasets that can work with the candela components exposed in the reference app. The script would be one of the "quick start" steps so the user doesn't need to create the special collections/folders and do the uploads by hand.

**Comment by alex-r-bigelow** [comment]
That's fine... just trying to figure out the best place to put things.

Maybe something like this?
```
candela
    /exampleCollections
        /Data
        /Toolchains
```
Is there any particular way you imagine we'd say that `/Toolchains/CarScatterplot` is *the* default toolchain for the scatterplot component?

**Comment by ronichoudhury** [comment]
Since these are specific to the reference app, I'd imagine them going somewhere under the reference app root. Something like what you've proposed, except:
- I would maybe just call the directory ``examples``
- If we don't want to call them "toolchains" we ought to think about a better name for them

**Comment by ronichoudhury** [comment]
Ah, I hadn't seen #93 yet :)

**Comment by jeffbaumes** [comment]
I like this

```
candela
  /app
    /resonant-reference-app
      /examples
        /Data
        /Toolchains
```

**Comment by ronichoudhury** [comment]
:+1:
