### ISSUE TITLE
Need a name for the reference app, as well as "toolchain"

### ISSUE THREAD

**Issue by alex-r-bigelow** [Kitware/candela#93]

**Comment by alex-r-bigelow** [comment]
So here are my proposals for the name, and I think we should pick one by Friday. We discussed renaming "mappings" earlier as well, so I've thrown that in.

| Mappings | Toolchain   | Reference App |
|-------------|-------------|---------------|
| Matching | Composition | Harmony |
| Connections / Hononga* | Bola | Poi |
| Links | Braid** | Cat's Cradle / Gummitwist / Heraklas |
| Matching | Sanada*** | Haigō**** |

\* Maori: connections
** Reference to braid theory
*** Japanese: singular braid stitch (again, reference to braid theory)
**** Japanese: combination / harmony / mixture

My wife mentioned that "harmony" may be a little too close to "eHarmony," and it only conjures up images of angsty people, but I'll leave it in the running for now.

**Comment by ronichoudhury** [comment]
I wanted to add "Virtuoso" as a name for the application. But I don't particularly like it - too pretentious/arrogant.

**Comment by ronichoudhury** [comment]
If we don't like "mappings" then I think something more concrete like "visual variables" or "visual encodings" would be better than a more abstract name. (Though I actually think "mappings" is fine in this context. Maybe I need a reminder about why "mappings" might be confusing.)

**Comment by alex-r-bigelow** [comment]
I think we wanted do avoid confusion with geographic maps ... if / when we add geojs stuff, the terms may get overloaded.

I think the trickiest thing for me is renaming "toolchain"... if we can find a good name for that, the rest should come naturally. I guess "harmony" could work for "toolchain", with "virtuoso" or something in that vein for the app?

**Comment by ronichoudhury** [comment]
I still think that we should use a more mundane term for the toolchain and use a vivid one for the app as a whole.

Assuming the app name is "Harmony", I even think something as simple as "project" would work: "Create ~~an empty~~ a new project", "Project settings", "A project connects datasets to visualizations", "If your project is public...", "You can edit this project", etc.

That sounds pretty solid to me.

**Comment by ronichoudhury** [comment]
I'm leaning towards "visual mappings" for "mappings". I have faith that users won't be confused by the overloading with cartographic maps.

**Comment by ronichoudhury** [comment]
Other possible names for the app: Quartz (a computer-engineering example of a useful resonant object), Rhythm, Melody.

Quartz is a fairly well-known OSX thing of course.

In my mind, "Harmony" and "Quartz" are topping the short list at the moment (despite the former's possible association with Neil Clark Warren).

**Comment by jeffbaumes** [comment]
I feel we can only have one "new" name for the entirety of the app
(Harmony). Everything else should be generic. Data, Visual Mappings,
Visualization for the components and Workbook for the toolchain seem
reasonable to me. If we want to get more clever we can potentially add
cleverness in the future (e.g. achievements could have musical names,
etc.). I think if you start too complex and clever it detracts from the
dead-simple app that we want to convey. I would call toolchains
"Visualizations" (because that's what they are right now), but I think
Workbook lets us move to visual analytics, filtering, dashboards in the
future.

BTW I showed the Reference App to some of our Arbor team yesterday and they
loved it. They immediately wanted tree support as well so we could have a
discussion about that next week.

Jeff

**Comment by ronichoudhury** [comment]
Agreed.

I'd prefer "workbook" or "project" to "visualization" for exactly the reasons Jeff stated.

Are we coalescing around "Harmony"?

**Comment by alex-r-bigelow** [comment]
Here's where I'm leaning:

Mappings -> Matching
Even if the overloading term with geography isn't a problem, "mapping" still feels like a mathy term that we CS-types like. "Matching" feels slightly more like a game, and a bit more general-audience accessible (and technically the graph theory term is still correct).

Toolchain -> Project
"Workbook" feels like some burdensome assignment... and calling it a "visualization" would definitely be confusing (we'd have to then change other terminology to stuff like "chart" or "view"...)

I'm still not sold on Harmony... eHarmony still feels too close to me. And, as you observed, Quartz is taken. Ideally, I'd like to find a name that's clearly on its own.

**Comment by jeffbaumes** [comment]
Matching/Project is ok with me.

How about Resonant Share? Evokes simplicity, community. Also, zero
additional brands.

**Comment by ronichoudhury** [comment]
I like "Resonant Share" a lot, though it might still be a little bit
confusing, since "share" is a de facto feature of social-media-enriched
applications these days. What about "Resonant Laboratory" or "Resonant
Lab"? "Share" is good too though.

**Comment by alex-r-bigelow** [comment]
Ooh, I like Resonant Laboratory a lot.

**Comment by jeffbaumes** [comment]
I like Resonant Laboratory too! Should we ship it?

**Comment by alex-r-bigelow** [comment]
Sounds good to me. I'll start a rebrand branch.

**Comment by ronichoudhury** [comment]
Just to be clear, we've got:

App name: Resonant Laboratory
Toolchain rename: Project
Mapping rename: Matching

Is that right?

**Comment by jeffbaumes** [comment]
That's my understanding.

**Comment by alex-r-bigelow** [comment]
Fixed in 3103f6c23575b5d720e7f3b57fb207f04ae77c8d
