### ISSUE TITLE
Jupyter bindings

### ISSUE THREAD

**Issue by jeffbaumes** [Kitware/candela#94]
So this happened today after a few minutes of playing around

![screen shot 2016-04-06 at 7 35 37 am](https://cloud.githubusercontent.com/assets/81305/14315355/92e5e152-fbca-11e5-8049-15e2907f9091.png)

I think it would be quite easy to build a tiny Python library that did this without needing JS code. The bindings would have easy ways to allow pandas dataframe input and we could easily pass a Python dict of options through to JS.

**Comment by ronichoudhury** [comment]
:open_mouth: cool!
